name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-d17qrlmmcj7s73c691fg \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          || echo "Deployment failed, check Render dashboard"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}